sudo: false

language: python

python:
 - "3.5"

addons:
  apt:
    packages:
    - parallel

install:
  - pip install -r requirements-py35-linux64.txt
  - pip install -e .

script:
  - nosetests --with-doctest -v -a'!slow'
