sudo: false

language: python

python:
 - "3.5"

addons:
  apt:
    packages:
    - parallel
    - libspatialindex-dev #FIXME

install:
  - pip install -r requirements-py36-linux64.txt
  - pip install -e .

script:
  - nosetests --with-doctest -v -a'!slow'

after_success:
  - pip install sphinx==1.3.6
  - cd doc/sphinx
  - make html
